### ISSUE TITLE
tdlib 模块

### ISSUE THREAD

**Issue by wuliang-1** [LuckRain7/arcgis-api-for-javascript-vue#1]
请问大佬 这个 tdlib 文件结构 哪里可以下载

**Comment by wuliang-1** [comment]
不胜感激 关注 加星

**Comment by LuckRain7** [comment]
> 请问大佬 这个 tdlib 文件结构 哪里可以下载

具体出处不太清楚，也是别人拷给我的。
链接：https://pan.baidu.com/s/1f-tAZCifWIlBK-08J_DCJA 
提取码：onqp

**Comment by wuliang-1** [comment]
感谢大佬

**Comment by renshengyiyijihe** [comment]
../../server.url.config 这个配置文件找不到啊

**Comment by Frewen** [comment]
> > 请问大佬 这个 tdlib 文件结构 哪里可以下载
> 
> 具体出处不太清楚，也是别人拷给我的。
> 链接：https://pan.baidu.com/s/1f-tAZCifWIlBK-08J_DCJA
> 提取码：onqp

请问这个文件是放在哪个位置? 可以实现自动加载?
